apiVersion: v1
kind: Secret

metadata:
  name: db-connection

type: Opaque

data:
  db_user: cG9zdGdyZXMuemR0ZnNhb3dvbmFrY2tuZmhycmE=
  db_password: QTNreSFWanJLcUVXeFNMWipkNlk=
  db_host: YXdzLTAtc2EtZWFzdC0xLnBvb2xlci5zdXBhYmFzZS5jb20=
  db_port: NjU0Mw==
  db_name: cG9zdGdyZXM=
